# Generated by Django 3.1 on 2020-10-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Courtwear', 'Courtwear'), ('Ceremonial', 'Ceremonial'), ('Accessories', 'Accessories')], default='Accessories', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='Store')),
            ],
        ),
    ]
