# Generated by Django 3.1 on 2020-10-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201018_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Courtwear', 'Courtwear'), ('Accessories', 'Accessories'), ('Ceremonial', 'Ceremonial')], default='Accessories', max_length=20),
        ),
    ]
