# Generated by Django 3.1 on 2020-10-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201025_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Courtwear', 'Courtwear'), ('Accessories', 'Accessories'), ('Ceremonial', 'Ceremonial')], default='Accessories', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='store.Size'),
        ),
    ]
