# Generated by Django 3.1 on 2020-10-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201025_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Courtwear', 'Courtwear'), ('Ceremonial', 'Ceremonial'), ('Accessories', 'Accessories')], default='Accessories', max_length=20),
        ),
    ]
