# Generated by Django 3.1 on 2020-10-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201025_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Courtwear', 'Courtwear'), ('Ceremonial', 'Ceremonial')], default='Accessories', max_length=20),
        ),
    ]
