# Generated by Django 3.1 on 2020-11-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201111_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_image', models.ImageField(upload_to='Store')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Courtwear', 'Courtwear'), ('Ceremonial', 'Ceremonial')], default='Accessories', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='other_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.otherimages'),
        ),
    ]
