# Generated by Django 3.1 on 2020-11-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201114_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ceremonial', 'Ceremonial'), ('Men', 'Men'), ('Accessories', 'Accessories'), ('Women', 'Women'), ('Courtwear', 'Courtwear')], default='Accessories', max_length=20),
        ),
    ]
