# Generated by Django 3.1 on 2020-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201115_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Courtwear', 'Courtwear'), ('Ceremonial', 'Ceremonial'), ('Women', 'Women'), ('Accessories', 'Accessories'), ('Men', 'Men')], default='Accessories', max_length=20),
        ),
    ]
