# Generated by Django 3.1 on 2020-10-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201019_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Abandoned', 'Abandoned'), ('InProgress', 'InProgress'), ('Finished', 'Finished')], default='Started', max_length=20),
        ),
    ]
